<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <NoWarn>$(NoWarn);NU1701;NETSDK1206;CS0169;CS0067;CS1998;CS4014;CS8601;CS8602;CS8604;CS8612;CS8618;CS8625;CS8632;CS8767</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\cheesecake.png" />
    <None Remove="Images\coffee.png" />
    <None Remove="Images\croissant.png" />
    <None Remove="Images\plov.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GMap.NET.WPF" Version="1.0.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Text.Json" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\cheesecake.png" />
    <Resource Include="Images\coffee.png" />
    <Resource Include="Images\croissant.png" />
    <Resource Include="Images\plov.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Utils\script.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
